pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    skipStagesAfterUnstable()
    disableConcurrentBuilds()
  }
  agent {
    kubernetes {
      inheritFrom 'c8y-hugo'
      defaultContainer 'default'
    }
  }
  environment {
    YUM_SRV = 'yum.cumulocity.com'
    YUM_USR = 'hudson'
    YUM_DEST_DIR = '/var/www/staticpage-guides/guides/'
    HUGO_PARAMS = ""
  }
  stages {
    stage('Checkout') {
      steps {
      checkout([
        $class: 'GitSCM', branches: [[name: 'master']],
        extensions: [[$class: 'CleanCheckout']],
        userRemoteConfigs: [[url: 'git@github.com:Cumulocity-IoT/c8y-docs.git', credentialsId:'Jenkins_ssh_ghec']] ])
      }
    }
    stage('Build') {
      steps {
        sh '''echo \"Starting hugo with params ${HUGO_PARAMS}\"
          ls
          hugo ${HUGO_PARAMS}'''
      }
    }
    stage('Deploy') {
      steps {
        sshagent(['jenkins-master']) {
          sh '''bash --login
          python /docsRepoScanner.py ./
          pwd
          ls
          cp output.json ./public/releases.json
          echo "rsync -e 'ssh -o StrictHostKeyChecking=no' -avh ./public/* ${YUM_USR}@${YUM_SRV}:${YUM_DEST_DIR} --delete"
          rsync -e 'ssh -o StrictHostKeyChecking=no' -avh ./public/* ${YUM_USR}@${YUM_SRV}:${YUM_DEST_DIR} --delete
          '''
        }
      }
    }
  }
}
