properties([
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')),
  disableConcurrentBuilds()
])

podTemplate(
  imagePullSecrets: ['ci-registry-pull'],
  containers: [
    containerTemplate(name:'hugo', image:'registry.stage.c8y.io/ci/c8y-ubuntu-hugo-deploy:latest', ttyEnabled:true,command: 'cat',
      envVars:[
        containerEnvVar(key:'YUM_SRV', value: 'yum.cumulocity.com'),
        containerEnvVar(key:'YUM_USR', value: 'hudson'),
        containerEnvVar(key:'YUM_DEST_DIR', value: '/var/www/staticpage-guides/guides/'),
      ]
    )
  ],yaml: """
          spec:
            securityContext:
              fsGroup: 1000
        """
)
{
node(POD_LABEL) {
  def HUGO_PARAMS = ""
  stage('Checkout') {
    container('docker') {
    checkout([
      $class: 'GitSCM', branches: [[name: 'carbon_migration']],
      extensions: [[$class: 'CleanCheckout']],
      userRemoteConfigs: [[url: 'git@bitbucket.org:m2m/c8y-docs.git',credentialsId:'jenkins-master']] ])
    }
  }
  stage('Build') {
    container('hugo') {

      sh '''echo \"Starting hugo with params ${HUGO_PARAMS}\"
        ls
        hugo ${HUGO_PARAMS}'''
    }
  }
  stage('Deploy') {
    container('hugo') {
      sshagent(['jenkins-master']) {
        sh '''bash --login
        python /docsRepoScanner.py ./
        pwd
        ls
        cp output.json ./public/releases.json
        echo "Disabled 'rsync -avh ./public/* ${YUM_USR}@${YUM_SRV}:${YUM_DEST_DIR} --delete'"
        '''
        sh "rsync -e 'ssh -o StrictHostKeyChecking=no' -avh ./public/* ${env.YUM_USR}@${env.YUM_SRV}:${YUM_DEST_DIR} --delete"
      }
    }
  }
 }
}
